#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : perl-autobox
Version  : 3.0.1
Release  : 1
URL      : https://cpan.metacpan.org/authors/id/C/CH/CHOCOLATE/autobox-v3.0.1.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/C/CH/CHOCOLATE/autobox-v3.0.1.tar.gz
Summary  : 'call methods on native types'
Group    : Development/Tools
License  : Artistic-2.0
Requires: perl-autobox-lib
Requires: perl-autobox-man
BuildRequires : perl(IPC::System::Simple)
BuildRequires : perl(Scope::Guard)
BuildRequires : perl(Test::Fatal)
BuildRequires : perl(Try::Tiny)

%description
autobox version 3.0.1
====================
The autobox pragma allows methods to be called on integers, floats, strings, arrays, hashes, and code references in exactly the same manner as blessed references.

%package lib
Summary: lib components for the perl-autobox package.
Group: Libraries

%description lib
lib components for the perl-autobox package.


%package man
Summary: man components for the perl-autobox package.
Group: Default

%description man
man components for the perl-autobox package.


%prep
%setup -q -n autobox-v3.0.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
if test -f Makefile.PL; then
%{__perl} Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot}
else
./Build install --installdirs=site --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)
/usr/lib/perl5/site_perl/5.26.1/x86_64-linux-thread-multi/autobox.pm
/usr/lib/perl5/site_perl/5.26.1/x86_64-linux-thread-multi/autobox.pod
/usr/lib/perl5/site_perl/5.26.1/x86_64-linux-thread-multi/autobox/universal.pm

%files lib
%defattr(-,root,root,-)
/usr/lib/perl5/site_perl/5.26.1/x86_64-linux-thread-multi/auto/autobox/autobox.so

%files man
%defattr(-,root,root,-)
/usr/share/man/man3/autobox.3
